# Regresión lineal múltiple con el método lstsq

In [1]:
import numpy as np
import pandas as pd
import time
import sys

En primer lugar cargamos el data set y realizamos las transformaciones necesarias de forma análoga a los casos anteriores

In [2]:
datos = pd.read_csv('./insurance.csv')
datos.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
datos['sex'].replace({'female' : 0, 'male' : 1}, inplace= True)
datos['smoker'].replace({'no': 0, 'yes': 1}, inplace= True)
datos = pd.get_dummies(datos)

In [4]:
X = datos.drop(['charges','region_northeast'], axis=1)

X.head()

age  sex     bmi  children  smoker  region_northwest  region_southeast  \
0   19    0  27.900         0       1                 0                 0   
1   18    1  33.770         1       0                 0                 1   
2   28    1  33.000         3       0                 0                 1   
3   33    1  22.705         0       0                 1                 0   
4   32    1  28.880         0       0                 1                 0   

   region_southwest  
0                 1  
1                 0  
2                 0  
3                 0  
4                 0

In [5]:
Y = datos['charges']
Y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [6]:
# Pasamos los datos a un array
X = X.values  
Y = np.array(Y)

In [7]:
X

array([[19.  ,  0.  , 27.9 , ...,  0.  ,  0.  ,  1.  ],
       [18.  ,  1.  , 33.77, ...,  0.  ,  1.  ,  0.  ],
       [28.  ,  1.  , 33.  , ...,  0.  ,  1.  ,  0.  ],
       ...,
       [18.  ,  0.  , 36.85, ...,  0.  ,  1.  ,  0.  ],
       [21.  ,  0.  , 25.8 , ...,  0.  ,  0.  ,  1.  ],
       [61.  ,  0.  , 29.07, ...,  1.  ,  0.  ,  0.  ]])

Para que tenga en cuenta el término independiente en la predicción, le añadimos una columna de 1 al array X.

In [8]:
X=np.vstack([np.ones(len(X)).T,X.T]).T

In [9]:
t1= time.time()

Ahora resolvemos el sistema ax = b

In [10]:
resultado = np.linalg.lstsq(X,Y)

/Users/lauraruizmartinez/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [11]:
t2=time.time()
tiempo = float(t2-t1)

print('Regresion lineal utilizando Numpy.linalg.lstsq()')
print("Tiempo de ejecucion: {} segundos".format(tiempo))

Regresion lineal utilizando Numpy.linalg.lstsq()
Tiempo de ejecucion: 0.026601076126098633 segundos


In [12]:
# Medimos el tamaño en bytes del objeto
print(sys.getsizeof(resultado), 'bytes')

80 bytes


Los coeficientes de la recta de regresión son:

In [13]:
resultado[0]

array([-11938.53857617,    256.85635254,   -131.3143594 ,    339.19345361,
          475.50054515,  23848.53454191,   -352.96389942,  -1035.02204939,
         -960.0509913 ])

Además el método nos proporciona la suma de los residuos

In [14]:
resultado[1]

array([4.88395328e+10])